backend:
  name: github
  repo: BigScrython/Cookbook
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "recipes"
    label: "Recipes"
    folder: "content/recipes"
    create: true
    slug: "{{slug}}"

    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Source", name: "source", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }

      - label: "Ingredients"
        name: "ingredients"
        widget: "list"

      - label: "Method"
        name: "method"
<<<<<<< HEAD
        widget: "list"
=======
        widget: "list"
>>>>>>> dbf196f37b7c2b8bb90564dfe560aea16e974600
